// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.


import Foundation
enum GlobalServers: Servers, ServerConvertible {
    /// Supported server value.
    ///
    /// Corresponds to `https://api.prod.speakeasyapi.dev`
    case prod

    /// Defines the raw URL strings for each server option.
    ///
    /// > Note: You do not need to use these values directly.
    ///
    /// The available URL strings are defined as:
    /// ```swift
    /// public static let urlStrings = [
    ///     "https://api.prod.speakeasyapi.dev"
    /// ]
    /// ```
    public static let urlStrings = [
        "https://api.prod.speakeasyapi.dev"
    ]

    func server() throws -> Server {
        switch self {
        case .prod:
          return try type(of: self).server(at: 0, substituting: nil)
        }
    }
}
