// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation
#if os(Linux)
import FoundationNetworking
#endif

public struct Response<T> {
    public var statusCode: Int {
        return httpResponse.statusCode
    }

    public var contentType: String {
        return httpResponse.contentType
    }

    public let httpResponse: HTTPURLResponse
    public let data: T
}
