// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.


import Foundation

class _EmbedsAPI: EmbedsAPI {
    private let client: Client

    init(client: Client) {
        self.client = client
    }
    
    public func getEmbedAccessToken(request: Operations.GetEmbedAccessTokenRequest) async throws -> Response<Operations.GetEmbedAccessTokenResponse> {
        return try await client.makeRequest(
            configureRequest: { configuration in
                try configureGetEmbedAccessTokenRequest(with: configuration, request: request)
            },
            handleResponse: handleGetEmbedAccessTokenResponse
        )
    }
    
    public func getValidEmbedAccessTokens() async throws -> Response<Operations.GetValidEmbedAccessTokensResponse> {
        return try await client.makeRequest(
            configureRequest: { configuration in
                try configureGetValidEmbedAccessTokensRequest(with: configuration)
            },
            handleResponse: handleGetValidEmbedAccessTokensResponse
        )
    }
    
    public func revokeEmbedAccessToken(request: Operations.RevokeEmbedAccessTokenRequest) async throws -> Response<Operations.RevokeEmbedAccessTokenResponse> {
        return try await client.makeRequest(
            configureRequest: { configuration in
                try configureRevokeEmbedAccessTokenRequest(with: configuration, request: request)
            },
            handleResponse: handleRevokeEmbedAccessTokenResponse
        )
    }

}

// MARK: - Request Configuration

private func configureGetEmbedAccessTokenRequest(with configuration: URLRequestConfiguration, request: Operations.GetEmbedAccessTokenRequest) throws {
    configuration.path = "/v1/workspace/embed-access-token"
    configuration.method = .get
    configuration.queryParameterSerializable = request
    configuration.telemetryHeader = .userAgent
}

private func configureGetValidEmbedAccessTokensRequest(with configuration: URLRequestConfiguration) throws {
    configuration.path = "/v1/workspace/embed-access-tokens/valid"
    configuration.method = .get
    configuration.telemetryHeader = .userAgent
}

private func configureRevokeEmbedAccessTokenRequest(with configuration: URLRequestConfiguration, request: Operations.RevokeEmbedAccessTokenRequest) throws {
    configuration.path = "/v1/workspace/embed-access-tokens/{tokenID}"
    configuration.method = .delete
    configuration.pathParameterSerializable = request
    configuration.telemetryHeader = .userAgent
}

// MARK: - Response Handlers

private func handleGetEmbedAccessTokenResponse(response: Client.APIResponse) throws -> Operations.GetEmbedAccessTokenResponse {
    let httpResponse = response.httpResponse
    
    if httpResponse.statusCode == 200 { 
        if httpResponse.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                return .embedAccessTokenResponse(try JSONDecoder().decode(Shared.EmbedAccessTokenResponse.self, from: data))
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    } else { 
        if httpResponse.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                return .error(try JSONDecoder().decode(Shared.Error.self, from: data))
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    }

    return .empty
}

private func handleGetValidEmbedAccessTokensResponse(response: Client.APIResponse) throws -> Operations.GetValidEmbedAccessTokensResponse {
    let httpResponse = response.httpResponse
    
    if httpResponse.statusCode == 200 { 
        if httpResponse.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                return .embedTokens(try JSONDecoder().decode([Shared.EmbedToken].self, from: data))
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    } else { 
        if httpResponse.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                return .error(try JSONDecoder().decode(Shared.Error.self, from: data))
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    }

    return .empty
}

private func handleRevokeEmbedAccessTokenResponse(response: Client.APIResponse) throws -> Operations.RevokeEmbedAccessTokenResponse {
    let httpResponse = response.httpResponse
    
    if httpResponse.statusCode == 200 { 
    } else { 
        if httpResponse.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                return .error(try JSONDecoder().decode(Shared.Error.self, from: data))
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    }

    return .empty
}

