// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.


import Foundation

extension Client: MetadataAPI { 
    public func deleteVersionMetadata(request: Operations.DeleteVersionMetadataRequest) async throws -> Response<Operations.DeleteVersionMetadataResponse> {
        return try await makeRequest(
            configureRequest: { configuration in
                try configureDeleteVersionMetadataRequest(with: configuration, request: request)
            },
            handleResponse: handleDeleteVersionMetadataResponse
        )
    }
    public func getVersionMetadata(request: Operations.GetVersionMetadataRequest) async throws -> Response<Operations.GetVersionMetadataResponse> {
        return try await makeRequest(
            configureRequest: { configuration in
                try configureGetVersionMetadataRequest(with: configuration, request: request)
            },
            handleResponse: handleGetVersionMetadataResponse
        )
    }
    public func insertVersionMetadata(request: Operations.InsertVersionMetadataRequest) async throws -> Response<Operations.InsertVersionMetadataResponse> {
        return try await makeRequest(
            configureRequest: { configuration in
                try configureInsertVersionMetadataRequest(with: configuration, request: request)
            },
            handleResponse: handleInsertVersionMetadataResponse
        )
    }
}

// MARK: - Request Configuration

private func configureDeleteVersionMetadataRequest(with configuration: URLRequestConfiguration, request: Operations.DeleteVersionMetadataRequest) throws {
    configuration.path = "/v1/apis/{apiID}/version/{versionID}/metadata/{metaKey}/{metaValue}"
    configuration.method = .delete
    configuration.pathParameterSerializable = request
    configuration.telemetryHeader = .userAgent
}

private func configureGetVersionMetadataRequest(with configuration: URLRequestConfiguration, request: Operations.GetVersionMetadataRequest) throws {
    configuration.path = "/v1/apis/{apiID}/version/{versionID}/metadata"
    configuration.method = .get
    configuration.pathParameterSerializable = request
    configuration.telemetryHeader = .userAgent
}

private func configureInsertVersionMetadataRequest(with configuration: URLRequestConfiguration, request: Operations.InsertVersionMetadataRequest) throws {
    configuration.path = "/v1/apis/{apiID}/version/{versionID}/metadata"
    configuration.method = .post
    configuration.pathParameterSerializable = request
    configuration.contentType = "application/json"
    configuration.body = try jsonEncoder().encode(request.versionMetadataInput)
    if configuration.body == nil {
        throw SerializationError.missingRequiredRequestBody
    }
    configuration.telemetryHeader = .userAgent
}

// MARK: - Response Handlers

private func handleDeleteVersionMetadataResponse(response: Client.APIResponse) throws -> Operations.DeleteVersionMetadataResponse {
    let httpResponse = response.httpResponse
    
    if httpResponse.statusCode == 200 { 
    } else { 
        if httpResponse.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                return .error(try JSONDecoder().decode(Shared.Error.self, from: data))
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    }

    return .empty
}

private func handleGetVersionMetadataResponse(response: Client.APIResponse) throws -> Operations.GetVersionMetadataResponse {
    let httpResponse = response.httpResponse
    
    if httpResponse.statusCode == 200 { 
        if httpResponse.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                return .versionMetadata(try JSONDecoder().decode([Shared.VersionMetadata].self, from: data))
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    } else { 
        if httpResponse.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                return .error(try JSONDecoder().decode(Shared.Error.self, from: data))
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    }

    return .empty
}

private func handleInsertVersionMetadataResponse(response: Client.APIResponse) throws -> Operations.InsertVersionMetadataResponse {
    let httpResponse = response.httpResponse
    
    if httpResponse.statusCode == 200 { 
        if httpResponse.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                return .versionMetadata(try JSONDecoder().decode(Shared.VersionMetadata.self, from: data))
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    } else { 
        if httpResponse.contentType.matchContentType(pattern: "application/json"), let data = response.data {
            do {
                return .error(try JSONDecoder().decode(Shared.Error.self, from: data))
            } catch {
                throw ResponseHandlerError.failedToDecodeJSON(error)
            }
        }
    }

    return .empty
}

